# Generated by Django 4.1.7 on 2023-02-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=64, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videos.video', verbose_name='Video'),
        ),
    ]
